using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ANcpLua.Agents.Testing.BitNet.Generators;

/// <summary>
///     Incremental generator that turns <c>[BitNet]</c> on a partial test class into the full xUnit v3
///     fixture wiring — the collection attribute, the fixture-injecting constructor, a <c>BitNet</c>
///     accessor, and a <c>SkipUnlessBitNetAvailable()</c> helper — plus one
///     <c>[CollectionDefinition] : ICollectionFixture&lt;BitNetFixture&gt;</c> per distinct collection
///     name in the consuming assembly, so a test class needs no fixture boilerplate of its own. Targets
///     must be non-generic, top-level <c>partial class</c>es.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BitNetFixtureGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "ANcpLua.Agents.Testing.BitNet.BitNetAttribute";
    private const string FixtureType = "global::ANcpLua.Agents.Testing.BitNet.BitNetFixture";
    private const string DefaultCollection = "BitNet";

    private static readonly DiagnosticDescriptor s_mustBePartial = new(
        "BITNET001",
        "[BitNet] type must be partial",
        "Type '{0}' is marked [BitNet] but is not declared 'partial'; the generated fixture wiring cannot be added",
        "ANcpLua.Agents.Testing.BitNet",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor s_mustNotBeNested = new(
        "BITNET002",
        "[BitNet] type must be top-level",
        "Type '{0}' is marked [BitNet] but is nested; nested test classes are not supported",
        "ANcpLua.Agents.Testing.BitNet",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor s_mustNotBeGeneric = new(
        "BITNET003",
        "[BitNet] type must be non-generic",
        "Type '{0}' is marked [BitNet] but is generic; generic test classes are not supported",
        "ANcpLua.Agents.Testing.BitNet",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor s_mustNotDeclareConstructor = new(
        "BITNET004",
        "[BitNet] type must not declare a constructor",
        "Type '{0}' is marked [BitNet] but declares its own constructor; the generator owns the fixture constructor, so remove the hand-written one",
        "ANcpLua.Agents.Testing.BitNet",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => Model.From(ctx));

        // Per-class wiring (and diagnostics for invalid targets).
        context.RegisterSourceOutput(models, static (spc, model) => model.EmitClass(spc));

        // One [CollectionDefinition] per distinct collection name actually used by a valid [BitNet] class.
        var collectionNames = models
            .Where(static m => m.IsValid)
            .Select(static (m, _) => m.CollectionName)
            .Collect();
        context.RegisterSourceOutput(collectionNames, static (spc, names) => EmitCollectionDefinitions(spc, names));
    }

    private static void EmitCollectionDefinitions(SourceProductionContext spc, ImmutableArray<string> names)
    {
        if (names.IsDefaultOrEmpty) return;

        var distinct = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var name in names) distinct.Add(name);

        var sb = new StringBuilder(256);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by ANcpLua.Agents.Testing.BitNet.Generators. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ANcpLua.Agents.Testing.BitNet.Generated;");
        sb.AppendLine();

        var index = 0;
        foreach (var name in distinct)
        {
            sb.AppendLine("/// <summary>Generated xUnit collection fixture for [BitNet] test classes.</summary>");
            sb.Append("[global::Xunit.CollectionDefinition(");
            sb.Append(SymbolDisplay.FormatLiteral(name, quote: true));
            sb.AppendLine(")]");
            sb.Append("public sealed class BitNetCollectionDefinition_").Append(index)
                .Append(" : global::Xunit.ICollectionFixture<").Append(FixtureType).AppendLine(">;");
            sb.AppendLine();
            index++;
        }

        spc.AddSource("BitNetCollectionDefinitions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record LocationInfo(string FilePath, TextSpan TextSpan, LinePositionSpan LineSpan)
    {
        public Location ToLocation() => Location.Create(FilePath, TextSpan, LineSpan);

        public static LocationInfo From(Location location) =>
            new(location.SourceTree?.FilePath ?? string.Empty,
                location.SourceSpan,
                location.GetLineSpan().Span);
    }

    private sealed record Model(
        string? Namespace,
        string ClassName,
        string CollectionName,
        bool IsPartial,
        bool IsNested,
        bool IsGeneric,
        bool HasUserConstructor,
        string HintName,
        LocationInfo Location)
    {
        public bool IsValid => IsPartial && !IsNested && !IsGeneric && !HasUserConstructor;

        public static Model From(GeneratorAttributeSyntaxContext ctx)
        {
            var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
            var syntax = (ClassDeclarationSyntax)ctx.TargetNode;

            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();

            var collection = DefaultCollection;
            foreach (var attr in ctx.Attributes)
            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "Collection" && named.Value.Value is string { Length: > 0 } configured)
                    collection = configured;
            }

            var hint = (ns is null ? symbol.Name : ns + "." + symbol.Name) + ".BitNet.g.cs";

            return new Model(
                ns,
                symbol.Name,
                collection,
                IsPartial: syntax.Modifiers.Any(SyntaxKind.PartialKeyword),
                IsNested: symbol.ContainingType is not null,
                IsGeneric: symbol.TypeParameters.Length > 0,
                HasUserConstructor: symbol.InstanceConstructors.Any(static c => !c.IsImplicitlyDeclared),
                hint,
                LocationInfo.From(syntax.Identifier.GetLocation()));
        }

        public void EmitClass(SourceProductionContext spc)
        {
            if (IsNested)
            {
                spc.ReportDiagnostic(Diagnostic.Create(s_mustNotBeNested, Location.ToLocation(), ClassName));
                return;
            }

            if (IsGeneric)
            {
                spc.ReportDiagnostic(Diagnostic.Create(s_mustNotBeGeneric, Location.ToLocation(), ClassName));
                return;
            }

            if (!IsPartial)
            {
                spc.ReportDiagnostic(Diagnostic.Create(s_mustBePartial, Location.ToLocation(), ClassName));
                return;
            }

            if (HasUserConstructor)
            {
                spc.ReportDiagnostic(Diagnostic.Create(s_mustNotDeclareConstructor, Location.ToLocation(), ClassName));
                return;
            }

            var sb = new StringBuilder(512);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by ANcpLua.Agents.Testing.BitNet.Generators. Do not edit.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            if (Namespace is not null)
            {
                sb.Append("namespace ").Append(Namespace).AppendLine(";");
                sb.AppendLine();
            }

            sb.Append("[global::Xunit.Collection(");
            sb.Append(SymbolDisplay.FormatLiteral(CollectionName, quote: true));
            sb.AppendLine(")]");
            sb.Append("partial class ").AppendLine(ClassName);
            sb.AppendLine("{");
            sb.Append("    private readonly ").Append(FixtureType).AppendLine(" _bitNetFixture;");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Injected by xUnit from the shared BitNet collection fixture.</summary>");
            sb.Append("    public ").Append(ClassName).Append('(').Append(FixtureType).AppendLine(" bitNetFixture)");
            sb.AppendLine("        => _bitNetFixture = bitNetFixture;");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>The shared BitNet fixture: chat client, endpoint, and availability.</summary>");
            sb.Append("    protected ").Append(FixtureType).AppendLine(" BitNet => _bitNetFixture;");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Skips the current test unless the BitNet server answered the health probe.</summary>");
            sb.AppendLine("    protected void SkipUnlessBitNetAvailable()");
            sb.AppendLine("        => global::Xunit.Assert.SkipUnless(_bitNetFixture.IsAvailable, \"BitNet server is not available.\");");
            sb.AppendLine("}");

            spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
