using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ANcpLua.Agents.Hosting.BitNet.Generators;

/// <summary>
///     Incremental Roslyn generator that scans every
///     <c>[assembly: BitNetEndpoint(...)]</c> on the consuming assembly and emits a single
///     extension method <c>AddDiscoveredBitNetClients(this IHostApplicationBuilder)</c> that
///     calls <c>AddBitNetChatClient</c> once per declared endpoint.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BitNetEndpointGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "ANcpLua.Agents.Hosting.BitNet.BitNetEndpointAttribute";
    private const string GeneratedFileName = "BitNetDiscoveredEndpoints.g.cs";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var endpoints = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var attrSymbol = compilation.GetTypeByMetadataName(AttributeMetadataName);
            if (attrSymbol is null)
                return ImmutableArray<EndpointDeclaration>.Empty;

            var builder = ImmutableArray.CreateBuilder<EndpointDeclaration>();
            foreach (var attr in compilation.Assembly.GetAttributes())
            {
                if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attrSymbol))
                    continue;
                if (TryExtract(attr) is { } decl)
                    builder.Add(decl);
            }

            return builder.ToImmutable();
        });

        context.RegisterSourceOutput(endpoints, static (spc, declared) =>
        {
            if (declared.IsDefaultOrEmpty) return;
            var source = Emit(declared);
            spc.AddSource(GeneratedFileName, SourceText.From(source, Encoding.UTF8));
        });
    }

    private static EndpointDeclaration? TryExtract(AttributeData attr)
    {
        if (attr.ConstructorArguments.Length < 2) return null;
        if (attr.ConstructorArguments[0].Value is not string name) return null;
        if (attr.ConstructorArguments[1].Value is not string endpoint) return null;

        string? model = null;
        string? apiPath = null;
        var enableOpenTelemetry = true;
        string? openTelemetrySourceName = null;

        foreach (var named in attr.NamedArguments)
        {
            switch (named.Key)
            {
                case "Model":
                    model = named.Value.Value as string;
                    break;
                case "ApiPath":
                    apiPath = named.Value.Value as string;
                    break;
                case "EnableOpenTelemetry":
                    enableOpenTelemetry = named.Value.Value is not bool b || b;
                    break;
                case "OpenTelemetrySourceName":
                    openTelemetrySourceName = named.Value.Value as string;
                    break;
            }
        }

        return new EndpointDeclaration(name, endpoint, model, apiPath, enableOpenTelemetry, openTelemetrySourceName);
    }

    private static string Emit(ImmutableArray<EndpointDeclaration> declarations)
    {
        var sb = new StringBuilder(capacity: 512 + declarations.Length * 256);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by ANcpLua.Agents.Hosting.BitNet.Generators. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ANcpLua.Agents.Hosting.BitNet;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Generated extension that wires every <c>[assembly: BitNetEndpoint]</c>");
        sb.AppendLine("///     declared on the consuming assembly via <see cref=\"BitNetHostingExtensions.AddBitNetChatClient(global::Microsoft.Extensions.Hosting.IHostApplicationBuilder, string, global::System.Action{BitNetClientOptions}?)\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class BitNetDiscoveredEndpointsExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Wires every discovered <c>[assembly: BitNetEndpoint]</c> endpoint.</summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.Hosting.IHostApplicationBuilder AddDiscoveredBitNetClients(");
        sb.AppendLine("        this global::Microsoft.Extensions.Hosting.IHostApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (builder is null) throw new global::System.ArgumentNullException(nameof(builder));");
        sb.AppendLine();

        foreach (var decl in declarations)
        {
            sb.Append("        builder.AddBitNetChatClient(");
            AppendStringLiteral(sb, decl.Name);
            sb.AppendLine(", static options =>");
            sb.AppendLine("        {");
            sb.Append("            options.Endpoint = new global::System.Uri(");
            AppendStringLiteral(sb, decl.Endpoint);
            sb.AppendLine(");");
            if (decl.Model is not null)
            {
                sb.Append("            options.Model = ");
                AppendStringLiteral(sb, decl.Model);
                sb.AppendLine(";");
            }
            if (decl.ApiPath is not null)
            {
                sb.Append("            options.ApiPath = ");
                AppendStringLiteral(sb, decl.ApiPath);
                sb.AppendLine(";");
            }
            if (!decl.EnableOpenTelemetry)
                sb.AppendLine("            options.EnableOpenTelemetry = false;");
            if (decl.OpenTelemetrySourceName is not null)
            {
                sb.Append("            options.OpenTelemetrySourceName = ");
                AppendStringLiteral(sb, decl.OpenTelemetrySourceName);
                sb.AppendLine(";");
            }
            sb.AppendLine("        });");
        }

        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // SymbolDisplay.FormatLiteral handles every escape case (quotes, control chars, unicode)
    // and never throws on malformed inputs — safer than hand-rolling \\ and \" escapes.
    private static void AppendStringLiteral(StringBuilder sb, string value) =>
        sb.Append(SymbolDisplay.FormatLiteral(value, quote: true));

    private sealed record EndpointDeclaration(
        string Name,
        string Endpoint,
        string? Model,
        string? ApiPath,
        bool EnableOpenTelemetry,
        string? OpenTelemetrySourceName);
}
